build_image:
    variables: 
        CI_DEBUG_TRACE: "true"

    stage: build
    services:
        - docker:18.05.0-ce-dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --build-arg GIT_COMMIT_HASH="$CI_COMMIT_SHA" -f Dockerfile .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Urcime ze kterych vetvi / tagu se ma image buildovat
    only:
        - int
        - master
        - tags
    # tag container nam rika ze bude image buildovat worker ktery umi zpracovavat kroky s tagem container
    tags:
        - container